import os

TELEGRAM_TOKEN_DEV = "131224483:AAG6kbFxGJ-QeK0Ju5wIivu-dc8EZ7ZVeWc"
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", TELEGRAM_TOKEN_DEV)

PERSISTANCE_FILE = "ASEBOT.PICKLE"

API_SERVER = "https://ase.bot.co.za"
TSEHAI_IMAGE_URL = API_SERVER+"/uploads/tsehai_93aec6be25.jpeg"
GRAPHQL_ENDPOINT = API_SERVER+"/graphql" 