class USER:
    REPEAT_VISITOR = "REPEAT_VISITOR"
    READING_LEVEL = "READING_LEVEL"
    QUIZZ_TAKEN = "QUIZZ_TAKEN"

class STATE:
    STARTED = "STARTED"
    BROWSE_BOOKS = "BROWSE_BOOKS"
    READ_BOOK = "READ_BOOK"
    NEXT_BOOK = "NEXT_BOOK"
    READING = "READING"
    QUIZZ = "QUIZZ"
    READINGLEVEL = "READINGLEVEL"
    END = -1
